# .github/workflows/main.yml
name: Terraform AWS Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configurar a AWS CLI com Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1 # Altere para sua região

      # Instalar o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 5.82.2 # Use a versão adequada

      # Inicializar o Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      # Validar os arquivos Terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/

      # Planejar as mudanças
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: terraform/

      # Aplicar as mudanças
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' # Só aplica no branch main
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/
