# .github/workflows/main.yml
name: Terraform AWS Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Escolha a ação a ser executada: apply ou destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout Code
        uses: actions/checkout@v3

      # Listar arquivos do repositório (para depuração)
      - name: List Repository Files
        run: ls -R

      # Configurar Credenciais AWS com Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      # Instalar o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7
          terraform_wrapper: false

      # Inicializar o Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: Terraform/

      # Validar os arquivos Terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: Terraform/

      # Planejar as mudanças (para apply)
      - name: Terraform Plan for Apply
        if: github.event.inputs.action == 'apply'
        id: plan
        run: terraform plan -out=tfplan
        working-directory: Terraform/

      # Executar Terraform Apply
      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan
        working-directory: Terraform/

      # Planejar as mudanças (para destroy)
      - name: Terraform Plan for Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform plan -destroy -out=tfdestroy
        working-directory: Terraform/

      # Executar Terraform Destroy
      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform apply -auto-approve tfdestroy
        working-directory: Terraform/
